"""
bundle_data.py — copies every file in data/processed/ into ONE JavaScript file:
    site/js/data_bundle.js

Why: browsers block loading JSON files when you double-click index.html (file://).
The bundle lets the site work even then. When the site runs on a web server
(python3 -m http.server), it reads the JSON files directly and ignores the bundle.

Run this after you change anything in data/processed/:
    python3 scripts/bundle_data.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROCESSED = ROOT / "data" / "processed"
OUT = ROOT / "site" / "js" / "data_bundle.js"

files = {}
for path in sorted(PROCESSED.rglob("*")):
    if path.suffix in (".json", ".geojson"):
        key = path.relative_to(PROCESSED).as_posix()
        files[key] = json.loads(path.read_text())

OUT.write_text(
    "// AUTO-GENERATED by scripts/bundle_data.py. Do not edit by hand.\n"
    "window.DATA_BUNDLE = " + json.dumps(files, separators=(",", ":")) + ";\n"
)
print(f"Wrote {OUT.relative_to(ROOT)} with {len(files)} files ({OUT.stat().st_size // 1024} KB)")
